([rule220_1] of defeasible-rule
   (rule-name rule220_1)
   (original-rule "rule220_1 ( lc:case ( lc:defendant ?Defendant ) ( lc:uses_gross_violence \"true\" ) ) ( lc:case ( lc:defendant ?Defendant ) ( lc:violates_integrity \"family_member_yes\" ) ) => ( is_guilty_of_family_violence_lv1 ( defendant ?Defendant ) )")
   (condition-classes)
   (conclusion-class is_guilty_of_family_violence_lv1)
   (negated no)
   (superior)
   (deductive-rule rule220_1-deductive)
   (overruled-rule rule220_1-overruled)
   (system no)
   (support-rule rule220_1-support)
   (defeasibly-rule rule220_1-defeasibly)
   (defeated-rule nil))

([rule220_2] of defeasible-rule
   (rule-name rule220_2)
   (original-rule "rule220_2 ( lc:case ( lc:defendant ?Defendant ) ( lc:uses_gross_violence \"true\" ) ) ( lc:case ( lc:defendant ?Defendant ) ( lc:violates_integrity \"family_member_yes\" ) ) ( lc:case ( lc:defendant ?Defendant ) ( lc:uses_weapon \"true\" ) ) => ( is_guilty_of_family_violence_lv2 ( defendant ?Defendant ) )")
   (condition-classes)
   (conclusion-class is_guilty_of_family_violence_lv2)
   (negated no)
   (superior)
   (deductive-rule rule220_2-deductive)
   (overruled-rule rule220_2-overruled)
   (system no)
   (support-rule rule220_2-support)
   (defeasibly-rule rule220_2-defeasibly)
   (defeated-rule nil))

([rule220_2_neg] of defeasible-rule
   (rule-name rule220_2_neg)
   (original-rule "rule220_2_neg ( declare ( superior rule220_1 ) ) ( is_guilty_of_family_violence_lv2 ( defendant ?Defendant ) ) => ( not ( is_guilty_of_family_violence_lv1 ( defendant ?Defendant ) ) )")
   (condition-classes)
   (conclusion-class is_guilty_of_family_violence_lv1)
   (negated yes)
   (superior rule220_1)
   (deductive-rule rule220_2_neg-deductive)
   (overruled-rule rule220_2_neg-overruled)
   (system no)
   (support-rule rule220_2_neg-support)
   (defeasibly-rule rule220_2_neg-defeasibly)
   (defeated-rule rule220_2_neg-defeated))

([rule220_3_a] of defeasible-rule
   (rule-name rule220_3_a)
   (original-rule "rule220_3_a ( lc:case ( lc:defendant ?Defendant ) ( lc:uses_gross_violence \"true\" ) ) ( lc:case ( lc:defendant ?Defendant ) ( lc:violates_integrity \"family_member_yes\" ) ) ( lc:case ( lc:defendant ?Defendant ) ( lc:uses_weapon \"true\" ) ) ( lc:case ( lc:defendant ?Defendant ) ( lc:causes_serious_injury \"true\" ) ) => ( is_guilty_of_family_violence_lv3 ( defendant ?Defendant ) )")
   (condition-classes)
   (conclusion-class is_guilty_of_family_violence_lv3)
   (negated no)
   (superior)
   (deductive-rule rule220_3_a-deductive)
   (overruled-rule rule220_3_a-overruled)
   (system no)
   (support-rule rule220_3_a-support)
   (defeasibly-rule rule220_3_a-defeasibly)
   (defeated-rule nil))

([rule220_3_b] of defeasible-rule
   (rule-name rule220_3_b)
   (original-rule "rule220_3_b ( lc:case ( lc:defendant ?Defendant ) ( lc:uses_gross_violence \"true\" ) ) ( lc:case ( lc:defendant ?Defendant ) ( lc:violates_integrity \"family_member_yes\" ) ) ( lc:case ( lc:defendant ?Defendant ) ( lc:uses_weapon \"true\" ) ) ( lc:case ( lc:defendant ?Defendant ) ( lc:victim_is_minor \"true\" ) ) => ( is_guilty_of_family_violence_lv3 ( defendant ?Defendant ) )")
   (condition-classes)
   (conclusion-class is_guilty_of_family_violence_lv3)
   (negated no)
   (superior)
   (deductive-rule rule220_3_b-deductive)
   (overruled-rule rule220_3_b-overruled)
   (system no)
   (support-rule rule220_3_b-support)
   (defeasibly-rule rule220_3_b-defeasibly)
   (defeated-rule nil))

([rule220_3_neg_1] of defeasible-rule
   (rule-name rule220_3_neg_1)
   (original-rule "rule220_3_neg_1 ( declare ( superior rule220_1 ) ) ( is_guilty_of_family_violence_lv3 ( defendant ?Defendant ) ) => ( not ( is_guilty_of_family_violence_lv1 ( defendant ?Defendant ) ) )")
   (condition-classes)
   (conclusion-class is_guilty_of_family_violence_lv1)
   (negated yes)
   (superior rule220_1)
   (deductive-rule rule220_3_neg_1-deductive)
   (overruled-rule rule220_3_neg_1-overruled)
   (system no)
   (support-rule rule220_3_neg_1-support)
   (defeasibly-rule rule220_3_neg_1-defeasibly)
   (defeated-rule rule220_3_neg_1-defeated))

([rule220_3_neg_2] of defeasible-rule
   (rule-name rule220_3_neg_2)
   (original-rule "rule220_3_neg_2 ( declare ( superior rule220_2 ) ) ( is_guilty_of_family_violence_lv3 ( defendant ?Defendant ) ) => ( not ( is_guilty_of_family_violence_lv2 ( defendant ?Defendant ) ) )")
   (condition-classes)
   (conclusion-class is_guilty_of_family_violence_lv2)
   (negated yes)
   (superior rule220_2)
   (deductive-rule rule220_3_neg_2-deductive)
   (overruled-rule rule220_3_neg_2-overruled)
   (system no)
   (support-rule rule220_3_neg_2-support)
   (defeasibly-rule rule220_3_neg_2-defeasibly)
   (defeated-rule rule220_3_neg_2-defeated))

([rule220_4] of defeasible-rule
   (rule-name rule220_4)
   (original-rule "rule220_4 ( lc:case ( lc:defendant ?Defendant ) ( lc:uses_gross_violence \"true\" ) ) ( lc:case ( lc:defendant ?Defendant ) ( lc:violates_integrity \"family_member_yes\" ) ) ( lc:case ( lc:defendant ?Defendant ) ( lc:uses_weapon \"true\" ) ) ( lc:case ( lc:defendant ?Defendant ) ( lc:causes_death \"true\" ) ) => ( is_guilty_of_family_violence_lv4 ( defendant ?Defendant ) )")
   (condition-classes)
   (conclusion-class is_guilty_of_family_violence_lv4)
   (negated no)
   (superior)
   (deductive-rule rule220_4-deductive)
   (overruled-rule rule220_4-overruled)
   (system no)
   (support-rule rule220_4-support)
   (defeasibly-rule rule220_4-defeasibly)
   (defeated-rule nil))

([rule220_4_neg_1] of defeasible-rule
   (rule-name rule220_4_neg_1)
   (original-rule "rule220_4_neg_1 ( declare ( superior rule220_1 ) ) ( is_guilty_of_family_violence_lv4 ( defendant ?Defendant ) ) => ( not ( is_guilty_of_family_violence_lv1 ( defendant ?Defendant ) ) )")
   (condition-classes)
   (conclusion-class is_guilty_of_family_violence_lv1)
   (negated yes)
   (superior rule220_1)
   (deductive-rule rule220_4_neg_1-deductive)
   (overruled-rule rule220_4_neg_1-overruled)
   (system no)
   (support-rule rule220_4_neg_1-support)
   (defeasibly-rule rule220_4_neg_1-defeasibly)
   (defeated-rule rule220_4_neg_1-defeated))

([rule220_4_neg_2] of defeasible-rule
   (rule-name rule220_4_neg_2)
   (original-rule "rule220_4_neg_2 ( declare ( superior rule220_2 ) ) ( is_guilty_of_family_violence_lv4 ( defendant ?Defendant ) ) => ( not ( is_guilty_of_family_violence_lv2 ( defendant ?Defendant ) ) )")
   (condition-classes)
   (conclusion-class is_guilty_of_family_violence_lv2)
   (negated yes)
   (superior rule220_2)
   (deductive-rule rule220_4_neg_2-deductive)
   (overruled-rule rule220_4_neg_2-overruled)
   (system no)
   (support-rule rule220_4_neg_2-support)
   (defeasibly-rule rule220_4_neg_2-defeasibly)
   (defeated-rule rule220_4_neg_2-defeated))

([rule220_4_neg_3] of defeasible-rule
   (rule-name rule220_4_neg_3)
   (original-rule "rule220_4_neg_3 ( declare ( superior rule220_3_a rule220_3_b ) ) ( is_guilty_of_family_violence_lv4 ( defendant ?Defendant ) ) => ( not ( is_guilty_of_family_violence_lv3 ( defendant ?Defendant ) ) )")
   (condition-classes)
   (conclusion-class is_guilty_of_family_violence_lv3)
   (negated yes)
   (superior rule220_3_a rule220_3_b)
   (deductive-rule rule220_4_neg_3-deductive)
   (overruled-rule rule220_4_neg_3-overruled)
   (system no)
   (support-rule rule220_4_neg_3-support)
   (defeasibly-rule rule220_4_neg_3-defeasibly)
   (defeated-rule rule220_4_neg_3-defeated))

([rule220_5] of defeasible-rule
   (rule-name rule220_5)
   (original-rule "rule220_5 ( lc:case ( lc:defendant ?Defendant ) ( lc:violates_protection_measures \"true\" ) ) => ( is_guilty_of_violating_measures ( defendant ?Defendant ) )")
   (condition-classes)
   (conclusion-class is_guilty_of_violating_measures)
   (negated no)
   (superior)
   (deductive-rule rule220_5-deductive)
   (overruled-rule rule220_5-overruled)
   (system no)
   (support-rule rule220_5-support)
   (defeasibly-rule rule220_5-defeasibly)
   (defeated-rule nil))

([rule220_5_neg_1] of defeasible-rule
   (rule-name rule220_5_neg_1)
   (original-rule "rule220_5_neg_1 ( declare ( superior rule220_5 ) ) ( is_guilty_of_family_violence_lv1 ( defendant ?Defendant ) ) => ( not ( is_guilty_of_violating_measures ( defendant ?Defendant ) ) )")
   (condition-classes)
   (conclusion-class is_guilty_of_violating_measures)
   (negated yes)
   (superior rule220_5)
   (deductive-rule rule220_5_neg_1-deductive)
   (overruled-rule rule220_5_neg_1-overruled)
   (system no)
   (support-rule rule220_5_neg_1-support)
   (defeasibly-rule rule220_5_neg_1-defeasibly)
   (defeated-rule rule220_5_neg_1-defeated))

([rule220_5_neg_2] of defeasible-rule
   (rule-name rule220_5_neg_2)
   (original-rule "rule220_5_neg_2 ( declare ( superior rule220_5 ) ) ( is_guilty_of_family_violence_lv2 ( defendant ?Defendant ) ) => ( not ( is_guilty_of_violating_measures ( defendant ?Defendant ) ) )")
   (condition-classes)
   (conclusion-class is_guilty_of_violating_measures)
   (negated yes)
   (superior rule220_5)
   (deductive-rule rule220_5_neg_2-deductive)
   (overruled-rule rule220_5_neg_2-overruled)
   (system no)
   (support-rule rule220_5_neg_2-support)
   (defeasibly-rule rule220_5_neg_2-defeasibly)
   (defeated-rule rule220_5_neg_2-defeated))

([rule220_5_neg_3] of defeasible-rule
   (rule-name rule220_5_neg_3)
   (original-rule "rule220_5_neg_3 ( declare ( superior rule220_5 ) ) ( is_guilty_of_family_violence_lv3 ( defendant ?Defendant ) ) => ( not ( is_guilty_of_violating_measures ( defendant ?Defendant ) ) )")
   (condition-classes)
   (conclusion-class is_guilty_of_violating_measures)
   (negated yes)
   (superior rule220_5)
   (deductive-rule rule220_5_neg_3-deductive)
   (overruled-rule rule220_5_neg_3-overruled)
   (system no)
   (support-rule rule220_5_neg_3-support)
   (defeasibly-rule rule220_5_neg_3-defeasibly)
   (defeated-rule rule220_5_neg_3-defeated))

([rule220_5_neg_4] of defeasible-rule
   (rule-name rule220_5_neg_4)
   (original-rule "rule220_5_neg_4 ( declare ( superior rule220_5 ) ) ( is_guilty_of_family_violence_lv4 ( defendant ?Defendant ) ) => ( not ( is_guilty_of_violating_measures ( defendant ?Defendant ) ) )")
   (condition-classes)
   (conclusion-class is_guilty_of_violating_measures)
   (negated yes)
   (superior rule220_5)
   (deductive-rule rule220_5_neg_4-deductive)
   (overruled-rule rule220_5_neg_4-overruled)
   (system no)
   (support-rule rule220_5_neg_4-support)
   (defeasibly-rule rule220_5_neg_4-defeasibly)
   (defeated-rule rule220_5_neg_4-defeated))

([rule221_1] of defeasible-rule
   (rule-name rule221_1)
   (original-rule "rule221_1 ( lc:case ( lc:defendant ?Defendant ) ( lc:legal_obligation_to_support \"true\" ) ) ( lc:case ( lc:defendant ?Defendant ) ( lc:duty_established_by_court_order \"true\" ) ) ( lc:case ( lc:defendant ?Defendant ) ( lc:fails_to_pay_support \"true\" ) ) => ( is_guilty_of_nonpayment_of_support_lv1 ( defendant ?Defendant ) )")
   (condition-classes)
   (conclusion-class is_guilty_of_nonpayment_of_support_lv1)
   (negated no)
   (superior)
   (deductive-rule rule221_1-deductive)
   (overruled-rule rule221_1-overruled)
   (system no)
   (support-rule rule221_1-support)
   (defeasibly-rule rule221_1-defeasibly)
   (defeated-rule nil))

([rule221_1_neg] of defeasible-rule
   (rule-name rule221_1_neg)
   (original-rule "rule221_1_neg ( declare ( superior rule221_1 ) ) ( lc:case ( lc:defendant ?Defendant ) ( lc:legal_obligation_to_support \"true\" ) ) ( lc:case ( lc:defendant ?Defendant ) ( lc:duty_established_by_court_order \"true\" ) ) ( lc:case ( lc:defendant ?Defendant ) ( lc:fails_to_pay_support \"true\" ) ) ( lc:case ( lc:defendant ?Defendant ) ( lc:justified_reasons_for_nonpayment \"true\" ) ) => ( not ( is_guilty_of_nonpayment_of_support_lv1 ( defendant ?Defendant ) ) )")
   (condition-classes)
   (conclusion-class is_guilty_of_nonpayment_of_support_lv1)
   (negated yes)
   (superior rule221_1)
   (deductive-rule rule221_1_neg-deductive)
   (overruled-rule rule221_1_neg-overruled)
   (system no)
   (support-rule rule221_1_neg-support)
   (defeasibly-rule rule221_1_neg-defeasibly)
   (defeated-rule rule221_1_neg-defeated))

([rule221_3] of defeasible-rule
   (rule-name rule221_3)
   (original-rule "rule221_3 ( lc:case ( lc:defendant ?Defendant ) ( lc:legal_obligation_to_support \"true\" ) ) ( lc:case ( lc:defendant ?Defendant ) ( lc:duty_established_by_court_order \"true\" ) ) ( lc:case ( lc:defendant ?Defendant ) ( lc:fails_to_pay_support \"true\" ) ) ( lc:case ( lc:defendant ?Defendant ) ( lc:justified_reasons_for_nonpayment \"false\" ) ) ( lc:case ( lc:defendant ?Defendant ) ( lc:severe_consequences_for_victim \"true\" ) ) => ( is_guilty_of_nonpayment_of_support_lv2 ( defendant ?Defendant ) )")
   (condition-classes)
   (conclusion-class is_guilty_of_nonpayment_of_support_lv2)
   (negated no)
   (superior)
   (deductive-rule rule221_3-deductive)
   (overruled-rule rule221_3-overruled)
   (system no)
   (support-rule rule221_3-support)
   (defeasibly-rule rule221_3-defeasibly)
   (defeated-rule nil))

([rule221_1_neg_3] of defeasible-rule
   (rule-name rule221_1_neg_3)
   (original-rule "rule221_1_neg_3 ( declare ( superior rule221_1 ) ) ( is_guilty_of_nonpayment_of_support_lv2 ( defendant ?Defendant ) ) => ( not ( is_guilty_of_nonpayment_of_support_lv1 ( defendant ?Defendant ) ) )")
   (condition-classes)
   (conclusion-class is_guilty_of_nonpayment_of_support_lv1)
   (negated yes)
   (superior rule221_1)
   (deductive-rule rule221_1_neg_3-deductive)
   (overruled-rule rule221_1_neg_3-overruled)
   (system no)
   (support-rule rule221_1_neg_3-support)
   (defeasibly-rule rule221_1_neg_3-defeasibly)
   (defeated-rule rule221_1_neg_3-defeated))

([pen220_1_fine] of defeasible-rule
   (rule-name pen220_1_fine)
   (original-rule "pen220_1_fine ( is_guilty_of_family_violence_lv1 ( defendant ?Defendant ) ) => ( to_pay ( value 1000 ) )")
   (condition-classes)
   (conclusion-class to_pay)
   (negated no)
   (superior)
   (deductive-rule pen220_1_fine-deductive)
   (overruled-rule pen220_1_fine-overruled)
   (system no)
   (support-rule pen220_1_fine-support)
   (defeasibly-rule pen220_1_fine-defeasibly)
   (defeated-rule nil))

([pen220_1_prison] of defeasible-rule
   (rule-name pen220_1_prison)
   (original-rule "pen220_1_prison ( is_guilty_of_family_violence_lv1 ( defendant ?Defendant ) ) => ( max_imprisonment ( value 2 ) )")
   (condition-classes)
   (conclusion-class max_imprisonment)
   (negated no)
   (superior)
   (deductive-rule pen220_1_prison-deductive)
   (overruled-rule pen220_1_prison-overruled)
   (system no)
   (support-rule pen220_1_prison-support)
   (defeasibly-rule pen220_1_prison-defeasibly)
   (defeated-rule nil))

([pen220_2_min] of defeasible-rule
   (rule-name pen220_2_min)
   (original-rule "pen220_2_min ( is_guilty_of_family_violence_lv2 ( defendant ?Defendant ) ) => ( min_imprisonment ( value 3 ) )")
   (condition-classes)
   (conclusion-class min_imprisonment)
   (negated no)
   (superior)
   (deductive-rule pen220_2_min-deductive)
   (overruled-rule pen220_2_min-overruled)
   (system no)
   (support-rule pen220_2_min-support)
   (defeasibly-rule pen220_2_min-defeasibly)
   (defeated-rule nil))

([pen220_2_max] of defeasible-rule
   (rule-name pen220_2_max)
   (original-rule "pen220_2_max ( is_guilty_of_family_violence_lv2 ( defendant ?Defendant ) ) => ( max_imprisonment ( value 3 ) )")
   (condition-classes)
   (conclusion-class max_imprisonment)
   (negated no)
   (superior)
   (deductive-rule pen220_2_max-deductive)
   (overruled-rule pen220_2_max-overruled)
   (system no)
   (support-rule pen220_2_max-support)
   (defeasibly-rule pen220_2_max-defeasibly)
   (defeated-rule nil))

([pen220_3_min] of defeasible-rule
   (rule-name pen220_3_min)
   (original-rule "pen220_3_min ( is_guilty_of_family_violence_lv3 ( defendant ?Defendant ) ) => ( min_imprisonment ( value 1 ) )")
   (condition-classes)
   (conclusion-class min_imprisonment)
   (negated no)
   (superior)
   (deductive-rule pen220_3_min-deductive)
   (overruled-rule pen220_3_min-overruled)
   (system no)
   (support-rule pen220_3_min-support)
   (defeasibly-rule pen220_3_min-defeasibly)
   (defeated-rule nil))

([pen220_3_max] of defeasible-rule
   (rule-name pen220_3_max)
   (original-rule "pen220_3_max ( is_guilty_of_family_violence_lv3 ( defendant ?Defendant ) ) => ( max_imprisonment ( value 5 ) )")
   (condition-classes)
   (conclusion-class max_imprisonment)
   (negated no)
   (superior)
   (deductive-rule pen220_3_max-deductive)
   (overruled-rule pen220_3_max-overruled)
   (system no)
   (support-rule pen220_3_max-support)
   (defeasibly-rule pen220_3_max-defeasibly)
   (defeated-rule nil))

([pen220_4_min] of defeasible-rule
   (rule-name pen220_4_min)
   (original-rule "pen220_4_min ( is_guilty_of_family_violence_lv4 ( defendant ?Defendant ) ) => ( min_imprisonment ( value 3 ) )")
   (condition-classes)
   (conclusion-class min_imprisonment)
   (negated no)
   (superior)
   (deductive-rule pen220_4_min-deductive)
   (overruled-rule pen220_4_min-overruled)
   (system no)
   (support-rule pen220_4_min-support)
   (defeasibly-rule pen220_4_min-defeasibly)
   (defeated-rule nil))

([pen220_4_max] of defeasible-rule
   (rule-name pen220_4_max)
   (original-rule "pen220_4_max ( is_guilty_of_family_violence_lv4 ( defendant ?Defendant ) ) => ( max_imprisonment ( value 12 ) )")
   (condition-classes)
   (conclusion-class max_imprisonment)
   (negated no)
   (superior)
   (deductive-rule pen220_4_max-deductive)
   (overruled-rule pen220_4_max-overruled)
   (system no)
   (support-rule pen220_4_max-support)
   (defeasibly-rule pen220_4_max-defeasibly)
   (defeated-rule nil))

([pen220_5_fine] of defeasible-rule
   (rule-name pen220_5_fine)
   (original-rule "pen220_5_fine ( is_guilty_of_violating_measures ( defendant ?Defendant ) ) => ( to_pay ( value 500 ) )")
   (condition-classes)
   (conclusion-class to_pay)
   (negated no)
   (superior)
   (deductive-rule pen220_5_fine-deductive)
   (overruled-rule pen220_5_fine-overruled)
   (system no)
   (support-rule pen220_5_fine-support)
   (defeasibly-rule pen220_5_fine-defeasibly)
   (defeated-rule nil))

([pen220_5_prison] of defeasible-rule
   (rule-name pen220_5_prison)
   (original-rule "pen220_5_prison ( is_guilty_of_violating_measures ( defendant ?Defendant ) ) => ( max_imprisonment ( value 1 ) )")
   (condition-classes)
   (conclusion-class max_imprisonment)
   (negated no)
   (superior)
   (deductive-rule pen220_5_prison-deductive)
   (overruled-rule pen220_5_prison-overruled)
   (system no)
   (support-rule pen220_5_prison-support)
   (defeasibly-rule pen220_5_prison-defeasibly)
   (defeated-rule nil))

([pen221_1_fine] of defeasible-rule
   (rule-name pen221_1_fine)
   (original-rule "pen221_1_fine ( is_guilty_of_nonpayment_of_support_lv1 ( defendant ?Defendant ) ) => ( to_pay ( value 300 ) )")
   (condition-classes)
   (conclusion-class to_pay)
   (negated no)
   (superior)
   (deductive-rule pen221_1_fine-deductive)
   (overruled-rule pen221_1_fine-overruled)
   (system no)
   (support-rule pen221_1_fine-support)
   (defeasibly-rule pen221_1_fine-defeasibly)
   (defeated-rule nil))

([pen221_1_prison] of defeasible-rule
   (rule-name pen221_1_prison)
   (original-rule "pen221_1_prison ( is_guilty_of_nonpayment_of_support_lv1 ( defendant ?Defendant ) ) => ( max_imprisonment ( value 2 ) )")
   (condition-classes)
   (conclusion-class max_imprisonment)
   (negated no)
   (superior)
   (deductive-rule pen221_1_prison-deductive)
   (overruled-rule pen221_1_prison-overruled)
   (system no)
   (support-rule pen221_1_prison-support)
   (defeasibly-rule pen221_1_prison-defeasibly)
   (defeated-rule nil))

([pen221_3_min] of defeasible-rule
   (rule-name pen221_3_min)
   (original-rule "pen221_3_min ( is_guilty_of_nonpayment_of_support_lv2 ( defendant ?Defendant ) ) => ( min_imprisonment ( value 6 ) )")
   (condition-classes)
   (conclusion-class min_imprisonment)
   (negated no)
   (superior)
   (deductive-rule pen221_3_min-deductive)
   (overruled-rule pen221_3_min-overruled)
   (system no)
   (support-rule pen221_3_min-support)
   (defeasibly-rule pen221_3_min-defeasibly)
   (defeated-rule nil))

([pen221_3_max] of defeasible-rule
   (rule-name pen221_3_max)
   (original-rule "pen221_3_max ( is_guilty_of_nonpayment_of_support_lv2 ( defendant ?Defendant ) ) => ( max_imprisonment ( value 5 ) )")
   (condition-classes)
   (conclusion-class max_imprisonment)
   (negated no)
   (superior)
   (deductive-rule pen221_3_max-deductive)
   (overruled-rule pen221_3_max-overruled)
   (system no)
   (support-rule pen221_3_max-support)
   (defeasibly-rule pen221_3_max-defeasibly)
   (defeated-rule nil))

