([is_guilty_of_family_violence_lv1] of defeasible-class
   (class-refs rdfs:isDefinedBy rdfs:Resource rdf:type rdfs:Class rdfs:seeAlso rdfs:Resource rdfs:subClassOf rdfs:Class rules defeasible-logic-rule)
   (aliases rdfs:seeAlso rdfs:isDefinedBy)
   (positive 0)
   (negative 0)
   (positive-derivator)
   (negative-derivator)
   (positive-support)
   (negative-support)
   (positive-overruled)
   (negative-overruled)
   (positive-defeated)
   (negative-defeated)
   (proof nil)
   (uri nil)
   (source rdf)
   (lc:causes_serious_consequences)
   (lc:fails_to_provide_support)
   (lc:violates_protection_measures)
   (lc:causes_death)
   (lc:causes_serious_injury)
   (lc:uses_weapon)
   (lc:violates_integrity)
   (lc:uses_gross_violence)
   (rdfs:isDefinedBy)
   (rdf:type [rdfs:Class])
   (rdf:value)
   (rdfs:comment)
   (rdfs:label is_guilty_of_family_violence_lv1)
   (rdfs:seeAlso)
   (rdfs:subClassOf [defeasible-class])
   (class-name is_guilty_of_family_violence_lv1)
   (rules [rule220_1])
   (defeasible-stratum 0))

([is_guilty_of_family_violence_lv2] of defeasible-class
   (class-refs rdfs:isDefinedBy rdfs:Resource rdf:type rdfs:Class rdfs:seeAlso rdfs:Resource rdfs:subClassOf rdfs:Class rules defeasible-logic-rule)
   (aliases rdfs:seeAlso rdfs:isDefinedBy)
   (positive 0)
   (negative 0)
   (positive-derivator)
   (negative-derivator)
   (positive-support)
   (negative-support)
   (positive-overruled)
   (negative-overruled)
   (positive-defeated)
   (negative-defeated)
   (proof nil)
   (uri nil)
   (source rdf)
   (lc:causes_serious_consequences)
   (lc:fails_to_provide_support)
   (lc:violates_protection_measures)
   (lc:causes_death)
   (lc:causes_serious_injury)
   (lc:uses_weapon)
   (lc:violates_integrity)
   (lc:uses_gross_violence)
   (rdfs:isDefinedBy)
   (rdf:type [rdfs:Class])
   (rdf:value)
   (rdfs:comment)
   (rdfs:label is_guilty_of_family_violence_lv2)
   (rdfs:seeAlso)
   (rdfs:subClassOf [defeasible-class])
   (class-name is_guilty_of_family_violence_lv2)
   (rules [rule220_2])
   (defeasible-stratum 0))

([max_imprisonment] of defeasible-class
   (class-refs rdfs:isDefinedBy rdfs:Resource rdf:type rdfs:Class rdfs:seeAlso rdfs:Resource rdfs:subClassOf rdfs:Class rules defeasible-logic-rule)
   (aliases rdfs:seeAlso rdfs:isDefinedBy)
   (positive 0)
   (negative 0)
   (positive-derivator)
   (negative-derivator)
   (positive-support)
   (negative-support)
   (positive-overruled)
   (negative-overruled)
   (positive-defeated)
   (negative-defeated)
   (proof nil)
   (uri nil)
   (source rdf)
   (lc:causes_serious_consequences)
   (lc:fails_to_provide_support)
   (lc:violates_protection_measures)
   (lc:causes_death)
   (lc:causes_serious_injury)
   (lc:uses_weapon)
   (lc:violates_integrity)
   (lc:uses_gross_violence)
   (rdfs:isDefinedBy)
   (rdf:type [rdfs:Class])
   (rdf:value)
   (rdfs:comment)
   (rdfs:label max_imprisonment)
   (rdfs:seeAlso)
   (rdfs:subClassOf [defeasible-class])
   (class-name max_imprisonment)
   (rules [pen220_2_max] [pen220_1])
   (defeasible-stratum 0))

([min_imprisonment] of defeasible-class
   (class-refs rdfs:isDefinedBy rdfs:Resource rdf:type rdfs:Class rdfs:seeAlso rdfs:Resource rdfs:subClassOf rdfs:Class rules defeasible-logic-rule)
   (aliases rdfs:seeAlso rdfs:isDefinedBy)
   (positive 0)
   (negative 0)
   (positive-derivator)
   (negative-derivator)
   (positive-support)
   (negative-support)
   (positive-overruled)
   (negative-overruled)
   (positive-defeated)
   (negative-defeated)
   (proof nil)
   (uri nil)
   (source rdf)
   (lc:causes_serious_consequences)
   (lc:fails_to_provide_support)
   (lc:violates_protection_measures)
   (lc:causes_death)
   (lc:causes_serious_injury)
   (lc:uses_weapon)
   (lc:violates_integrity)
   (lc:uses_gross_violence)
   (rdfs:isDefinedBy)
   (rdf:type [rdfs:Class])
   (rdf:value)
   (rdfs:comment)
   (rdfs:label min_imprisonment)
   (rdfs:seeAlso)
   (rdfs:subClassOf [defeasible-class])
   (class-name min_imprisonment)
   (rules [pen220_2_min])
   (defeasible-stratum 0))

