([rule220_1] of defeasible-rule
   (rule-name rule220_1)
   (original-rule "rule220_1 ( lc:case ( lc:defendant ?Defendant ) ) ( lc:case ( lc:defendant ?Defendant ) ( lc:violates_integrity \"family_member\" ) ) => ( is_guilty_of_family_violence_lv1 ( defendant ?Defendant ) )")
   (condition-classes)
   (conclusion-class is_guilty_of_family_violence_lv1)
   (negated no)
   (superior)
   (deductive-rule rule220_1-deductive)
   (overruled-rule rule220_1-overruled)
   (system no)
   (support-rule rule220_1-support)
   (defeasibly-rule rule220_1-defeasibly)
   (defeated-rule nil))

([rule220_2] of defeasible-rule
   (rule-name rule220_2)
   (original-rule "rule220_2 ( declare ( superior rule220_1 ) ) ( is_guilty_of_family_violence_lv1 ( defendant ?Defendant ) ) ( lc:case ( lc:defendant ?Defendant ) ) => ( is_guilty_of_family_violence_lv2 ( defendant ?Defendant ) )")
   (condition-classes)
   (conclusion-class is_guilty_of_family_violence_lv2)
   (negated no)
   (superior rule220_1)
   (deductive-rule rule220_2-deductive)
   (overruled-rule rule220_2-overruled)
   (system no)
   (support-rule rule220_2-support)
   (defeasibly-rule rule220_2-defeasibly)
   (defeated-rule rule220_2-defeated))

([pen220_1] of defeasible-rule
   (rule-name pen220_1)
   (original-rule "pen220_1 ( is_guilty_of_family_violence_lv1 ( defendant ?Defendant ) ) => ( max_imprisonment ( value 2 ) )")
   (condition-classes)
   (conclusion-class max_imprisonment)
   (negated no)
   (superior)
   (deductive-rule pen220_1-deductive)
   (overruled-rule pen220_1-overruled)
   (system no)
   (support-rule pen220_1-support)
   (defeasibly-rule pen220_1-defeasibly)
   (defeated-rule nil))

([pen220_2_min] of defeasible-rule
   (rule-name pen220_2_min)
   (original-rule "pen220_2_min ( is_guilty_of_family_violence_lv2 ( defendant ?Defendant ) ) => ( min_imprisonment ( value 3 ) )")
   (condition-classes)
   (conclusion-class min_imprisonment)
   (negated no)
   (superior)
   (deductive-rule pen220_2_min-deductive)
   (overruled-rule pen220_2_min-overruled)
   (system no)
   (support-rule pen220_2_min-support)
   (defeasibly-rule pen220_2_min-defeasibly)
   (defeated-rule nil))

([pen220_2_max] of defeasible-rule
   (rule-name pen220_2_max)
   (original-rule "pen220_2_max ( is_guilty_of_family_violence_lv2 ( defendant ?Defendant ) ) => ( max_imprisonment ( value 3 ) )")
   (condition-classes)
   (conclusion-class max_imprisonment)
   (negated no)
   (superior)
   (deductive-rule pen220_2_max-deductive)
   (overruled-rule pen220_2_max-overruled)
   (system no)
   (support-rule pen220_2_max-support)
   (defeasibly-rule pen220_2_max-defeasibly)
   (defeated-rule nil))

