([is_guilty_of_family_violence_lv1] of defeasible-class
   (class-refs rdfs:isDefinedBy rdfs:Resource rdf:type rdfs:Class rdfs:seeAlso rdfs:Resource rdfs:subClassOf rdfs:Class rules defeasible-logic-rule)
   (aliases rdfs:seeAlso rdfs:isDefinedBy)
   (positive 0)
   (negative 0)
   (positive-derivator)
   (negative-derivator)
   (positive-support)
   (negative-support)
   (positive-overruled)
   (negative-overruled)
   (positive-defeated)
   (negative-defeated)
   (proof nil)
   (uri nil)
   (source rdf)
   (lc:defendant)
   (lc:uses_gross_violence)
   (lc:violates_integrity)
   (rdfs:isDefinedBy)
   (rdf:type [rdfs:Class])
   (rdf:value)
   (rdfs:comment)
   (rdfs:label is_guilty_of_family_violence_lv1)
   (rdfs:seeAlso)
   (rdfs:subClassOf [defeasible-class])
   (class-name is_guilty_of_family_violence_lv1)
   (rules [rule220_2_neg] [rule220_1_neg] [rule220_1])
   (defeasible-stratum 0))

([is_guilty_of_family_violence_lv2] of defeasible-class
   (class-refs rdfs:isDefinedBy rdfs:Resource rdf:type rdfs:Class rdfs:seeAlso rdfs:Resource rdfs:subClassOf rdfs:Class rules defeasible-logic-rule)
   (aliases rdfs:seeAlso rdfs:isDefinedBy)
   (positive 0)
   (negative 0)
   (positive-derivator)
   (negative-derivator)
   (positive-support)
   (negative-support)
   (positive-overruled)
   (negative-overruled)
   (positive-defeated)
   (negative-defeated)
   (proof nil)
   (uri nil)
   (source rdf)
   (lc:defendant)
   (lc:uses_gross_violence)
   (lc:violates_integrity)
   (rdfs:isDefinedBy)
   (rdf:type [rdfs:Class])
   (rdf:value)
   (rdfs:comment)
   (rdfs:label is_guilty_of_family_violence_lv2)
   (rdfs:seeAlso)
   (rdfs:subClassOf [defeasible-class])
   (class-name is_guilty_of_family_violence_lv2)
   (rules [rule220_2])
   (defeasible-stratum 0))

([is_guilty_of_family_violence_lv3] of defeasible-class
   (class-refs rdfs:isDefinedBy rdfs:Resource rdf:type rdfs:Class rdfs:seeAlso rdfs:Resource rdfs:subClassOf rdfs:Class rules defeasible-logic-rule)
   (aliases rdfs:seeAlso rdfs:isDefinedBy)
   (positive 0)
   (negative 0)
   (positive-derivator)
   (negative-derivator)
   (positive-support)
   (negative-support)
   (positive-overruled)
   (negative-overruled)
   (positive-defeated)
   (negative-defeated)
   (proof nil)
   (uri nil)
   (source rdf)
   (lc:defendant)
   (lc:uses_gross_violence)
   (lc:violates_integrity)
   (rdfs:isDefinedBy)
   (rdf:type [rdfs:Class])
   (rdf:value)
   (rdfs:comment)
   (rdfs:label is_guilty_of_family_violence_lv3)
   (rdfs:seeAlso)
   (rdfs:subClassOf [defeasible-class])
   (class-name is_guilty_of_family_violence_lv3)
   (rules [rule220_3])
   (defeasible-stratum 0))

([is_guilty_of_family_violence_lv4] of defeasible-class
   (class-refs rdfs:isDefinedBy rdfs:Resource rdf:type rdfs:Class rdfs:seeAlso rdfs:Resource rdfs:subClassOf rdfs:Class rules defeasible-logic-rule)
   (aliases rdfs:seeAlso rdfs:isDefinedBy)
   (positive 0)
   (negative 0)
   (positive-derivator)
   (negative-derivator)
   (positive-support)
   (negative-support)
   (positive-overruled)
   (negative-overruled)
   (positive-defeated)
   (negative-defeated)
   (proof nil)
   (uri nil)
   (source rdf)
   (lc:defendant)
   (lc:uses_gross_violence)
   (lc:violates_integrity)
   (rdfs:isDefinedBy)
   (rdf:type [rdfs:Class])
   (rdf:value)
   (rdfs:comment)
   (rdfs:label is_guilty_of_family_violence_lv4)
   (rdfs:seeAlso)
   (rdfs:subClassOf [defeasible-class])
   (class-name is_guilty_of_family_violence_lv4)
   (rules [rule220_4])
   (defeasible-stratum 0))

([is_guilty_of_violating_measures] of defeasible-class
   (class-refs rdfs:isDefinedBy rdfs:Resource rdf:type rdfs:Class rdfs:seeAlso rdfs:Resource rdfs:subClassOf rdfs:Class rules defeasible-logic-rule)
   (aliases rdfs:seeAlso rdfs:isDefinedBy)
   (positive 0)
   (negative 0)
   (positive-derivator)
   (negative-derivator)
   (positive-support)
   (negative-support)
   (positive-overruled)
   (negative-overruled)
   (positive-defeated)
   (negative-defeated)
   (proof nil)
   (uri nil)
   (source rdf)
   (lc:defendant)
   (lc:uses_gross_violence)
   (lc:violates_integrity)
   (rdfs:isDefinedBy)
   (rdf:type [rdfs:Class])
   (rdf:value)
   (rdfs:comment)
   (rdfs:label is_guilty_of_violating_measures)
   (rdfs:seeAlso)
   (rdfs:subClassOf [defeasible-class])
   (class-name is_guilty_of_violating_measures)
   (rules [rule220_5])
   (defeasible-stratum 0))

([is_guilty_of_nonpayment_of_support_lv1] of defeasible-class
   (class-refs rdfs:isDefinedBy rdfs:Resource rdf:type rdfs:Class rdfs:seeAlso rdfs:Resource rdfs:subClassOf rdfs:Class rules defeasible-logic-rule)
   (aliases rdfs:seeAlso rdfs:isDefinedBy)
   (positive 0)
   (negative 0)
   (positive-derivator)
   (negative-derivator)
   (positive-support)
   (negative-support)
   (positive-overruled)
   (negative-overruled)
   (positive-defeated)
   (negative-defeated)
   (proof nil)
   (uri nil)
   (source rdf)
   (lc:defendant)
   (lc:uses_gross_violence)
   (lc:violates_integrity)
   (rdfs:isDefinedBy)
   (rdf:type [rdfs:Class])
   (rdf:value)
   (rdfs:comment)
   (rdfs:label is_guilty_of_nonpayment_of_support_lv1)
   (rdfs:seeAlso)
   (rdfs:subClassOf [defeasible-class])
   (class-name is_guilty_of_nonpayment_of_support_lv1)
   (rules [rule221_1])
   (defeasible-stratum 0))

([is_guilty_of_nonpayment_of_support_lv2] of defeasible-class
   (class-refs rdfs:isDefinedBy rdfs:Resource rdf:type rdfs:Class rdfs:seeAlso rdfs:Resource rdfs:subClassOf rdfs:Class rules defeasible-logic-rule)
   (aliases rdfs:seeAlso rdfs:isDefinedBy)
   (positive 0)
   (negative 0)
   (positive-derivator)
   (negative-derivator)
   (positive-support)
   (negative-support)
   (positive-overruled)
   (negative-overruled)
   (positive-defeated)
   (negative-defeated)
   (proof nil)
   (uri nil)
   (source rdf)
   (lc:defendant)
   (lc:uses_gross_violence)
   (lc:violates_integrity)
   (rdfs:isDefinedBy)
   (rdf:type [rdfs:Class])
   (rdf:value)
   (rdfs:comment)
   (rdfs:label is_guilty_of_nonpayment_of_support_lv2)
   (rdfs:seeAlso)
   (rdfs:subClassOf [defeasible-class])
   (class-name is_guilty_of_nonpayment_of_support_lv2)
   (rules [rule221_3])
   (defeasible-stratum 0))

([max_imprisonment] of defeasible-class
   (class-refs rdfs:isDefinedBy rdfs:Resource rdf:type rdfs:Class rdfs:seeAlso rdfs:Resource rdfs:subClassOf rdfs:Class rules defeasible-logic-rule)
   (aliases rdfs:seeAlso rdfs:isDefinedBy)
   (positive 0)
   (negative 0)
   (positive-derivator)
   (negative-derivator)
   (positive-support)
   (negative-support)
   (positive-overruled)
   (negative-overruled)
   (positive-defeated)
   (negative-defeated)
   (proof nil)
   (uri nil)
   (source rdf)
   (lc:defendant)
   (lc:uses_gross_violence)
   (lc:violates_integrity)
   (rdfs:isDefinedBy)
   (rdf:type [rdfs:Class])
   (rdf:value)
   (rdfs:comment)
   (rdfs:label max_imprisonment)
   (rdfs:seeAlso)
   (rdfs:subClassOf [defeasible-class])
   (class-name max_imprisonment)
   (rules [pen221_3_max] [pen221_1] [pen220_5] [pen220_4_max] [pen220_3_max] [pen220_2_max] [pen220_1])
   (defeasible-stratum 0))

([min_imprisonment] of defeasible-class
   (class-refs rdfs:isDefinedBy rdfs:Resource rdf:type rdfs:Class rdfs:seeAlso rdfs:Resource rdfs:subClassOf rdfs:Class rules defeasible-logic-rule)
   (aliases rdfs:seeAlso rdfs:isDefinedBy)
   (positive 0)
   (negative 0)
   (positive-derivator)
   (negative-derivator)
   (positive-support)
   (negative-support)
   (positive-overruled)
   (negative-overruled)
   (positive-defeated)
   (negative-defeated)
   (proof nil)
   (uri nil)
   (source rdf)
   (lc:defendant)
   (lc:uses_gross_violence)
   (lc:violates_integrity)
   (rdfs:isDefinedBy)
   (rdf:type [rdfs:Class])
   (rdf:value)
   (rdfs:comment)
   (rdfs:label min_imprisonment)
   (rdfs:seeAlso)
   (rdfs:subClassOf [defeasible-class])
   (class-name min_imprisonment)
   (rules [pen221_3_min] [pen220_4_min] [pen220_3_min] [pen220_2_min])
   (defeasible-stratum 0))

