([rule220_1] of defeasible-rule
   (rule-name rule220_1)
   (original-rule "rule220_1 ( lc:case ( lc:defendant ?Defendant ) ) ( lc:case ( lc:defendant ?Defendant ) ( lc:violates_integrity \"family_member\" ) ) => ( is_guilty_of_family_violence_lv1 ( defendant ?Defendant ) )")
   (condition-classes)
   (conclusion-class is_guilty_of_family_violence_lv1)
   (negated no)
   (superior)
   (deductive-rule rule220_1-deductive)
   (overruled-rule rule220_1-overruled)
   (system no)
   (support-rule rule220_1-support)
   (defeasibly-rule rule220_1-defeasibly)
   (defeated-rule nil))

([rule220_2] of defeasible-rule
   (rule-name rule220_2)
   (original-rule "rule220_2 ( declare ( superior rule220_1 ) ) ( is_guilty_of_family_violence_lv1 ( defendant ?Defendant ) ) ( lc:case ( lc:defendant ?Defendant ) ) => ( is_guilty_of_family_violence_lv2 ( defendant ?Defendant ) )")
   (condition-classes)
   (conclusion-class is_guilty_of_family_violence_lv2)
   (negated no)
   (superior rule220_1)
   (deductive-rule rule220_2-deductive)
   (overruled-rule rule220_2-overruled)
   (system no)
   (support-rule rule220_2-support)
   (defeasibly-rule rule220_2-defeasibly)
   (defeated-rule rule220_2-defeated))

([rule220_3] of defeasible-rule
   (rule-name rule220_3)
   (original-rule "rule220_3 ( declare ( superior rule220_2 ) ) ( is_guilty_of_family_violence_lv1 ( defendant ?Defendant ) ) => ( is_guilty_of_family_violence_lv3 ( defendant ?Defendant ) )")
   (condition-classes)
   (conclusion-class is_guilty_of_family_violence_lv3)
   (negated no)
   (superior rule220_2)
   (deductive-rule rule220_3-deductive)
   (overruled-rule rule220_3-overruled)
   (system no)
   (support-rule rule220_3-support)
   (defeasibly-rule rule220_3-defeasibly)
   (defeated-rule rule220_3-defeated))

([rule220_4] of defeasible-rule
   (rule-name rule220_4)
   (original-rule "rule220_4 ( declare ( superior rule220_3 ) ) ( is_guilty_of_family_violence_lv1 ( defendant ?Defendant ) ) ( lc:case ( lc:defendant ?Defendant ) ) => ( is_guilty_of_family_violence_lv4 ( defendant ?Defendant ) )")
   (condition-classes)
   (conclusion-class is_guilty_of_family_violence_lv4)
   (negated no)
   (superior rule220_3)
   (deductive-rule rule220_4-deductive)
   (overruled-rule rule220_4-overruled)
   (system no)
   (support-rule rule220_4-support)
   (defeasibly-rule rule220_4-defeasibly)
   (defeated-rule rule220_4-defeated))

([rule220_5] of defeasible-rule
   (rule-name rule220_5)
   (original-rule "rule220_5 ( lc:case ( lc:defendant ?Defendant ) ) => ( is_guilty_of_violating_measures ( defendant ?Defendant ) )")
   (condition-classes)
   (conclusion-class is_guilty_of_violating_measures)
   (negated no)
   (superior)
   (deductive-rule rule220_5-deductive)
   (overruled-rule rule220_5-overruled)
   (system no)
   (support-rule rule220_5-support)
   (defeasibly-rule rule220_5-defeasibly)
   (defeated-rule nil))

([rule221_1] of defeasible-rule
   (rule-name rule221_1)
   (original-rule "rule221_1 ( lc:case ( lc:defendant ?Defendant ) ) ( lc:case ( lc:defendant ?Defendant ) ) ( lc:case ( lc:defendant ?Defendant ) ) => ( is_guilty_of_nonpayment_of_support_lv1 ( defendant ?Defendant ) )")
   (condition-classes)
   (conclusion-class is_guilty_of_nonpayment_of_support_lv1)
   (negated no)
   (superior)
   (deductive-rule rule221_1-deductive)
   (overruled-rule rule221_1-overruled)
   (system no)
   (support-rule rule221_1-support)
   (defeasibly-rule rule221_1-defeasibly)
   (defeated-rule nil))

([rule221_3] of defeasible-rule
   (rule-name rule221_3)
   (original-rule "rule221_3 ( declare ( superior rule221_1 ) ) ( is_guilty_of_nonpayment_of_support_lv1 ( defendant ?Defendant ) ) ( lc:case ( lc:defendant ?Defendant ) ) => ( is_guilty_of_nonpayment_of_support_lv2 ( defendant ?Defendant ) )")
   (condition-classes)
   (conclusion-class is_guilty_of_nonpayment_of_support_lv2)
   (negated no)
   (superior rule221_1)
   (deductive-rule rule221_3-deductive)
   (overruled-rule rule221_3-overruled)
   (system no)
   (support-rule rule221_3-support)
   (defeasibly-rule rule221_3-defeasibly)
   (defeated-rule rule221_3-defeated))

([pen220_1] of defeasible-rule
   (rule-name pen220_1)
   (original-rule "pen220_1 ( is_guilty_of_family_violence_lv1 ( defendant ?Defendant ) ) => ( max_imprisonment ( value 2 ) )")
   (condition-classes)
   (conclusion-class max_imprisonment)
   (negated no)
   (superior)
   (deductive-rule pen220_1-deductive)
   (overruled-rule pen220_1-overruled)
   (system no)
   (support-rule pen220_1-support)
   (defeasibly-rule pen220_1-defeasibly)
   (defeated-rule nil))

([pen220_2_min] of defeasible-rule
   (rule-name pen220_2_min)
   (original-rule "pen220_2_min ( is_guilty_of_family_violence_lv2 ( defendant ?Defendant ) ) => ( min_imprisonment ( value 3 ) )")
   (condition-classes)
   (conclusion-class min_imprisonment)
   (negated no)
   (superior)
   (deductive-rule pen220_2_min-deductive)
   (overruled-rule pen220_2_min-overruled)
   (system no)
   (support-rule pen220_2_min-support)
   (defeasibly-rule pen220_2_min-defeasibly)
   (defeated-rule nil))

([pen220_2_max] of defeasible-rule
   (rule-name pen220_2_max)
   (original-rule "pen220_2_max ( is_guilty_of_family_violence_lv2 ( defendant ?Defendant ) ) => ( max_imprisonment ( value 3 ) )")
   (condition-classes)
   (conclusion-class max_imprisonment)
   (negated no)
   (superior)
   (deductive-rule pen220_2_max-deductive)
   (overruled-rule pen220_2_max-overruled)
   (system no)
   (support-rule pen220_2_max-support)
   (defeasibly-rule pen220_2_max-defeasibly)
   (defeated-rule nil))

([pen220_3_min] of defeasible-rule
   (rule-name pen220_3_min)
   (original-rule "pen220_3_min ( is_guilty_of_family_violence_lv3 ( defendant ?Defendant ) ) => ( min_imprisonment ( value 1 ) )")
   (condition-classes)
   (conclusion-class min_imprisonment)
   (negated no)
   (superior)
   (deductive-rule pen220_3_min-deductive)
   (overruled-rule pen220_3_min-overruled)
   (system no)
   (support-rule pen220_3_min-support)
   (defeasibly-rule pen220_3_min-defeasibly)
   (defeated-rule nil))

([pen220_3_max] of defeasible-rule
   (rule-name pen220_3_max)
   (original-rule "pen220_3_max ( is_guilty_of_family_violence_lv3 ( defendant ?Defendant ) ) => ( max_imprisonment ( value 5 ) )")
   (condition-classes)
   (conclusion-class max_imprisonment)
   (negated no)
   (superior)
   (deductive-rule pen220_3_max-deductive)
   (overruled-rule pen220_3_max-overruled)
   (system no)
   (support-rule pen220_3_max-support)
   (defeasibly-rule pen220_3_max-defeasibly)
   (defeated-rule nil))

([pen220_4_min] of defeasible-rule
   (rule-name pen220_4_min)
   (original-rule "pen220_4_min ( is_guilty_of_family_violence_lv4 ( defendant ?Defendant ) ) => ( min_imprisonment ( value 3 ) )")
   (condition-classes)
   (conclusion-class min_imprisonment)
   (negated no)
   (superior)
   (deductive-rule pen220_4_min-deductive)
   (overruled-rule pen220_4_min-overruled)
   (system no)
   (support-rule pen220_4_min-support)
   (defeasibly-rule pen220_4_min-defeasibly)
   (defeated-rule nil))

([pen220_4_max] of defeasible-rule
   (rule-name pen220_4_max)
   (original-rule "pen220_4_max ( is_guilty_of_family_violence_lv4 ( defendant ?Defendant ) ) => ( max_imprisonment ( value 12 ) )")
   (condition-classes)
   (conclusion-class max_imprisonment)
   (negated no)
   (superior)
   (deductive-rule pen220_4_max-deductive)
   (overruled-rule pen220_4_max-overruled)
   (system no)
   (support-rule pen220_4_max-support)
   (defeasibly-rule pen220_4_max-defeasibly)
   (defeated-rule nil))

([pen220_5] of defeasible-rule
   (rule-name pen220_5)
   (original-rule "pen220_5 ( is_guilty_of_violating_measures ( defendant ?Defendant ) ) => ( max_imprisonment ( value 1 ) )")
   (condition-classes)
   (conclusion-class max_imprisonment)
   (negated no)
   (superior)
   (deductive-rule pen220_5-deductive)
   (overruled-rule pen220_5-overruled)
   (system no)
   (support-rule pen220_5-support)
   (defeasibly-rule pen220_5-defeasibly)
   (defeated-rule nil))

([pen221_1] of defeasible-rule
   (rule-name pen221_1)
   (original-rule "pen221_1 ( is_guilty_of_nonpayment_of_support_lv1 ( defendant ?Defendant ) ) => ( max_imprisonment ( value 2 ) )")
   (condition-classes)
   (conclusion-class max_imprisonment)
   (negated no)
   (superior)
   (deductive-rule pen221_1-deductive)
   (overruled-rule pen221_1-overruled)
   (system no)
   (support-rule pen221_1-support)
   (defeasibly-rule pen221_1-defeasibly)
   (defeated-rule nil))

([pen221_3_min] of defeasible-rule
   (rule-name pen221_3_min)
   (original-rule "pen221_3_min ( is_guilty_of_nonpayment_of_support_lv2 ( defendant ?Defendant ) ) => ( min_imprisonment ( value 6 ) )")
   (condition-classes)
   (conclusion-class min_imprisonment)
   (negated no)
   (superior)
   (deductive-rule pen221_3_min-deductive)
   (overruled-rule pen221_3_min-overruled)
   (system no)
   (support-rule pen221_3_min-support)
   (defeasibly-rule pen221_3_min-defeasibly)
   (defeated-rule nil))

([pen221_3_max] of defeasible-rule
   (rule-name pen221_3_max)
   (original-rule "pen221_3_max ( is_guilty_of_nonpayment_of_support_lv2 ( defendant ?Defendant ) ) => ( max_imprisonment ( value 5 ) )")
   (condition-classes)
   (conclusion-class max_imprisonment)
   (negated no)
   (superior)
   (deductive-rule pen221_3_max-deductive)
   (overruled-rule pen221_3_max-overruled)
   (system no)
   (support-rule pen221_3_max-support)
   (defeasibly-rule pen221_3_max-defeasibly)
   (defeated-rule nil))

