( defclass is_guilty_of_family_violence_lv1 ( is-a DERIVED-CLASS ) ( slot defendant ( type ?VARIABLE ) ) )
( defclass is_guilty_of_family_violence_lv2 ( is-a DERIVED-CLASS ) ( slot defendant ( type ?VARIABLE ) ) )
( defclass is_guilty_of_family_violence_lv3 ( is-a DERIVED-CLASS ) ( slot defendant ( type ?VARIABLE ) ) )
( defclass is_guilty_of_family_violence_lv4 ( is-a DERIVED-CLASS ) ( slot defendant ( type ?VARIABLE ) ) )
( defclass is_guilty_of_violating_measures ( is-a DERIVED-CLASS ) ( slot defendant ( type ?VARIABLE ) ) )
( defclass is_guilty_of_nonpayment_of_support_lv1 ( is-a DERIVED-CLASS ) ( slot defendant ( type ?VARIABLE ) ) )
( defclass is_guilty_of_nonpayment_of_support_lv2 ( is-a DERIVED-CLASS ) ( slot defendant ( type ?VARIABLE ) ) )
( defclass to_pay ( is-a DERIVED-CLASS ) ( slot value ( type INTEGER ) ) ( slot unit ( type SYMBOL ) ) )
( defclass max_imprisonment ( is-a DERIVED-CLASS ) ( slot value ( type INTEGER ) ) ( slot unit ( type SYMBOL ) ) )
( defclass min_imprisonment ( is-a DERIVED-CLASS ) ( slot value ( type INTEGER ) ) ( slot unit ( type SYMBOL ) ) )
