([is_guilty_of_family_violence_lv1-derived-class] of derived-class-inst
   (class-refs rdfs:isDefinedBy rdfs:Resource rdf:type rdfs:Class rdfs:seeAlso rdfs:Resource rdfs:subClassOf rdfs:Class deductive-rules r-device-rule)
   (aliases rdfs:seeAlso rdfs:isDefinedBy)
   (positive 0)
   (negative 0)
   (positive-derivator)
   (negative-derivator)
   (positive-support)
   (negative-support)
   (positive-overruled)
   (negative-overruled)
   (positive-defeated)
   (negative-defeated)
   (proof nil)
   (uri nil)
   (source rdf)
   (lc:causes_serious_consequences)
   (lc:fails_to_provide_support)
   (lc:violates_protection_measures)
   (lc:causes_death)
   (lc:causes_serious_injury)
   (lc:uses_weapon)
   (lc:violates_integrity)
   (lc:uses_gross_violence)
   (rdfs:isDefinedBy)
   (rdf:type [rdfs:Class])
   (rdf:value)
   (rdfs:comment)
   (rdfs:label is_guilty_of_family_violence_lv1)
   (rdfs:seeAlso)
   (rdfs:subClassOf [derived-class-inst])
   (stratum 0)
   (deductive-rules [rule220_1-deductive-gen195]))

([is_guilty_of_family_violence_lv2-derived-class] of derived-class-inst
   (class-refs rdfs:isDefinedBy rdfs:Resource rdf:type rdfs:Class rdfs:seeAlso rdfs:Resource rdfs:subClassOf rdfs:Class deductive-rules r-device-rule)
   (aliases rdfs:seeAlso rdfs:isDefinedBy)
   (positive 0)
   (negative 0)
   (positive-derivator)
   (negative-derivator)
   (positive-support)
   (negative-support)
   (positive-overruled)
   (negative-overruled)
   (positive-defeated)
   (negative-defeated)
   (proof nil)
   (uri nil)
   (source rdf)
   (lc:causes_serious_consequences)
   (lc:fails_to_provide_support)
   (lc:violates_protection_measures)
   (lc:causes_death)
   (lc:causes_serious_injury)
   (lc:uses_weapon)
   (lc:violates_integrity)
   (lc:uses_gross_violence)
   (rdfs:isDefinedBy)
   (rdf:type [rdfs:Class])
   (rdf:value)
   (rdfs:comment)
   (rdfs:label is_guilty_of_family_violence_lv2)
   (rdfs:seeAlso)
   (rdfs:subClassOf [derived-class-inst])
   (stratum 0)
   (deductive-rules [rule220_2-deductive-gen196]))

([is_guilty_of_family_violence_lv3-derived-class] of derived-class-inst
   (class-refs rdfs:isDefinedBy rdfs:Resource rdf:type rdfs:Class rdfs:seeAlso rdfs:Resource rdfs:subClassOf rdfs:Class deductive-rules r-device-rule)
   (aliases rdfs:seeAlso rdfs:isDefinedBy)
   (positive 0)
   (negative 0)
   (positive-derivator)
   (negative-derivator)
   (positive-support)
   (negative-support)
   (positive-overruled)
   (negative-overruled)
   (positive-defeated)
   (negative-defeated)
   (proof nil)
   (uri nil)
   (source rdf)
   (lc:causes_serious_consequences)
   (lc:fails_to_provide_support)
   (lc:violates_protection_measures)
   (lc:causes_death)
   (lc:causes_serious_injury)
   (lc:uses_weapon)
   (lc:violates_integrity)
   (lc:uses_gross_violence)
   (rdfs:isDefinedBy)
   (rdf:type [rdfs:Class])
   (rdf:value)
   (rdfs:comment)
   (rdfs:label is_guilty_of_family_violence_lv3)
   (rdfs:seeAlso)
   (rdfs:subClassOf [derived-class-inst])
   (stratum 0)
   (deductive-rules [rule220_3-deductive-gen197]))

([is_guilty_of_family_violence_lv4-derived-class] of derived-class-inst
   (class-refs rdfs:isDefinedBy rdfs:Resource rdf:type rdfs:Class rdfs:seeAlso rdfs:Resource rdfs:subClassOf rdfs:Class deductive-rules r-device-rule)
   (aliases rdfs:seeAlso rdfs:isDefinedBy)
   (positive 0)
   (negative 0)
   (positive-derivator)
   (negative-derivator)
   (positive-support)
   (negative-support)
   (positive-overruled)
   (negative-overruled)
   (positive-defeated)
   (negative-defeated)
   (proof nil)
   (uri nil)
   (source rdf)
   (lc:causes_serious_consequences)
   (lc:fails_to_provide_support)
   (lc:violates_protection_measures)
   (lc:causes_death)
   (lc:causes_serious_injury)
   (lc:uses_weapon)
   (lc:violates_integrity)
   (lc:uses_gross_violence)
   (rdfs:isDefinedBy)
   (rdf:type [rdfs:Class])
   (rdf:value)
   (rdfs:comment)
   (rdfs:label is_guilty_of_family_violence_lv4)
   (rdfs:seeAlso)
   (rdfs:subClassOf [derived-class-inst])
   (stratum 0)
   (deductive-rules [rule220_4-deductive-gen198]))

([is_guilty_of_violating_measures-derived-class] of derived-class-inst
   (class-refs rdfs:isDefinedBy rdfs:Resource rdf:type rdfs:Class rdfs:seeAlso rdfs:Resource rdfs:subClassOf rdfs:Class deductive-rules r-device-rule)
   (aliases rdfs:seeAlso rdfs:isDefinedBy)
   (positive 0)
   (negative 0)
   (positive-derivator)
   (negative-derivator)
   (positive-support)
   (negative-support)
   (positive-overruled)
   (negative-overruled)
   (positive-defeated)
   (negative-defeated)
   (proof nil)
   (uri nil)
   (source rdf)
   (lc:causes_serious_consequences)
   (lc:fails_to_provide_support)
   (lc:violates_protection_measures)
   (lc:causes_death)
   (lc:causes_serious_injury)
   (lc:uses_weapon)
   (lc:violates_integrity)
   (lc:uses_gross_violence)
   (rdfs:isDefinedBy)
   (rdf:type [rdfs:Class])
   (rdf:value)
   (rdfs:comment)
   (rdfs:label is_guilty_of_violating_measures)
   (rdfs:seeAlso)
   (rdfs:subClassOf [derived-class-inst])
   (stratum 0)
   (deductive-rules [rule220_5-deductive-gen199]))

([is_guilty_of_nonpayment_of_support_lv1-derived-class] of derived-class-inst
   (class-refs rdfs:isDefinedBy rdfs:Resource rdf:type rdfs:Class rdfs:seeAlso rdfs:Resource rdfs:subClassOf rdfs:Class deductive-rules r-device-rule)
   (aliases rdfs:seeAlso rdfs:isDefinedBy)
   (positive 0)
   (negative 0)
   (positive-derivator)
   (negative-derivator)
   (positive-support)
   (negative-support)
   (positive-overruled)
   (negative-overruled)
   (positive-defeated)
   (negative-defeated)
   (proof nil)
   (uri nil)
   (source rdf)
   (lc:causes_serious_consequences)
   (lc:fails_to_provide_support)
   (lc:violates_protection_measures)
   (lc:causes_death)
   (lc:causes_serious_injury)
   (lc:uses_weapon)
   (lc:violates_integrity)
   (lc:uses_gross_violence)
   (rdfs:isDefinedBy)
   (rdf:type [rdfs:Class])
   (rdf:value)
   (rdfs:comment)
   (rdfs:label is_guilty_of_nonpayment_of_support_lv1)
   (rdfs:seeAlso)
   (rdfs:subClassOf [derived-class-inst])
   (stratum 0)
   (deductive-rules [rule221_1-deductive-gen200]))

([is_guilty_of_nonpayment_of_support_lv2-derived-class] of derived-class-inst
   (class-refs rdfs:isDefinedBy rdfs:Resource rdf:type rdfs:Class rdfs:seeAlso rdfs:Resource rdfs:subClassOf rdfs:Class deductive-rules r-device-rule)
   (aliases rdfs:seeAlso rdfs:isDefinedBy)
   (positive 0)
   (negative 0)
   (positive-derivator)
   (negative-derivator)
   (positive-support)
   (negative-support)
   (positive-overruled)
   (negative-overruled)
   (positive-defeated)
   (negative-defeated)
   (proof nil)
   (uri nil)
   (source rdf)
   (lc:causes_serious_consequences)
   (lc:fails_to_provide_support)
   (lc:violates_protection_measures)
   (lc:causes_death)
   (lc:causes_serious_injury)
   (lc:uses_weapon)
   (lc:violates_integrity)
   (lc:uses_gross_violence)
   (rdfs:isDefinedBy)
   (rdf:type [rdfs:Class])
   (rdf:value)
   (rdfs:comment)
   (rdfs:label is_guilty_of_nonpayment_of_support_lv2)
   (rdfs:seeAlso)
   (rdfs:subClassOf [derived-class-inst])
   (stratum 0)
   (deductive-rules [rule221_3-deductive-gen201]))

([max_imprisonment-derived-class] of derived-class-inst
   (class-refs rdfs:isDefinedBy rdfs:Resource rdf:type rdfs:Class rdfs:seeAlso rdfs:Resource rdfs:subClassOf rdfs:Class deductive-rules r-device-rule)
   (aliases rdfs:seeAlso rdfs:isDefinedBy)
   (positive 0)
   (negative 0)
   (positive-derivator)
   (negative-derivator)
   (positive-support)
   (negative-support)
   (positive-overruled)
   (negative-overruled)
   (positive-defeated)
   (negative-defeated)
   (proof nil)
   (uri nil)
   (source rdf)
   (lc:causes_serious_consequences)
   (lc:fails_to_provide_support)
   (lc:violates_protection_measures)
   (lc:causes_death)
   (lc:causes_serious_injury)
   (lc:uses_weapon)
   (lc:violates_integrity)
   (lc:uses_gross_violence)
   (rdfs:isDefinedBy)
   (rdf:type [rdfs:Class])
   (rdf:value)
   (rdfs:comment)
   (rdfs:label max_imprisonment)
   (rdfs:seeAlso)
   (rdfs:subClassOf [derived-class-inst])
   (stratum 0)
   (deductive-rules [pen221_3_max-deductive-gen212] [pen221_1-deductive-gen210] [pen220_5-deductive-gen209] [pen220_4_max-deductive-gen208] [pen220_3_max-deductive-gen206] [pen220_2_max-deductive-gen204] [pen220_1-deductive-gen202]))

([min_imprisonment-derived-class] of derived-class-inst
   (class-refs rdfs:isDefinedBy rdfs:Resource rdf:type rdfs:Class rdfs:seeAlso rdfs:Resource rdfs:subClassOf rdfs:Class deductive-rules r-device-rule)
   (aliases rdfs:seeAlso rdfs:isDefinedBy)
   (positive 0)
   (negative 0)
   (positive-derivator)
   (negative-derivator)
   (positive-support)
   (negative-support)
   (positive-overruled)
   (negative-overruled)
   (positive-defeated)
   (negative-defeated)
   (proof nil)
   (uri nil)
   (source rdf)
   (lc:causes_serious_consequences)
   (lc:fails_to_provide_support)
   (lc:violates_protection_measures)
   (lc:causes_death)
   (lc:causes_serious_injury)
   (lc:uses_weapon)
   (lc:violates_integrity)
   (lc:uses_gross_violence)
   (rdfs:isDefinedBy)
   (rdf:type [rdfs:Class])
   (rdf:value)
   (rdfs:comment)
   (rdfs:label min_imprisonment)
   (rdfs:seeAlso)
   (rdfs:subClassOf [derived-class-inst])
   (stratum 0)
   (deductive-rules [pen221_3_min-deductive-gen211] [pen220_4_min-deductive-gen207] [pen220_3_min-deductive-gen205] [pen220_2_min-deductive-gen203]))

