([is_guilty_of_family_violence_lv1-derived-class] of derived-class-inst
   (class-refs rdfs:isDefinedBy rdfs:Resource rdf:type rdfs:Class rdfs:seeAlso rdfs:Resource rdfs:subClassOf rdfs:Class deductive-rules r-device-rule)
   (aliases rdfs:seeAlso rdfs:isDefinedBy)
   (positive 0)
   (negative 0)
   (positive-derivator)
   (negative-derivator)
   (positive-support)
   (negative-support)
   (positive-overruled)
   (negative-overruled)
   (positive-defeated)
   (negative-defeated)
   (proof nil)
   (uri nil)
   (source rdf)
   (lc:name)
   (lc:defendant)
   (lc:uses_weapon)
   (lc:uses_gross_violence)
   (lc:violates_integrity)
   (lc:causes_serious_injury)
   (lc:victim_is_minor)
   (lc:causes_death)
   (lc:violates_protection_measures)
   (lc:legal_obligation_to_support)
   (lc:duty_established_by_court_order)
   (lc:fails_to_pay_support)
   (lc:justified_reasons_for_nonpayment)
   (lc:severe_consequences_for_victim)
   (rdfs:isDefinedBy)
   (rdf:type [rdfs:Class])
   (rdf:value)
   (rdfs:comment)
   (rdfs:label is_guilty_of_family_violence_lv1)
   (rdfs:seeAlso)
   (rdfs:subClassOf [derived-class-inst])
   (stratum 0)
   (deductive-rules [rule220_4_neg_1-deductive-gen410] [rule220_3_neg_1-deductive-gen407] [rule220_2_neg-deductive-gen404] [rule220_1-deductive-gen402]))

([is_guilty_of_family_violence_lv2-derived-class] of derived-class-inst
   (class-refs rdfs:isDefinedBy rdfs:Resource rdf:type rdfs:Class rdfs:seeAlso rdfs:Resource rdfs:subClassOf rdfs:Class deductive-rules r-device-rule)
   (aliases rdfs:seeAlso rdfs:isDefinedBy)
   (positive 0)
   (negative 0)
   (positive-derivator)
   (negative-derivator)
   (positive-support)
   (negative-support)
   (positive-overruled)
   (negative-overruled)
   (positive-defeated)
   (negative-defeated)
   (proof nil)
   (uri nil)
   (source rdf)
   (lc:name)
   (lc:defendant)
   (lc:uses_weapon)
   (lc:uses_gross_violence)
   (lc:violates_integrity)
   (lc:causes_serious_injury)
   (lc:victim_is_minor)
   (lc:causes_death)
   (lc:violates_protection_measures)
   (lc:legal_obligation_to_support)
   (lc:duty_established_by_court_order)
   (lc:fails_to_pay_support)
   (lc:justified_reasons_for_nonpayment)
   (lc:severe_consequences_for_victim)
   (rdfs:isDefinedBy)
   (rdf:type [rdfs:Class])
   (rdf:value)
   (rdfs:comment)
   (rdfs:label is_guilty_of_family_violence_lv2)
   (rdfs:seeAlso)
   (rdfs:subClassOf [derived-class-inst])
   (stratum 0)
   (deductive-rules [rule220_4_neg_2-deductive-gen411] [rule220_3_neg_2-deductive-gen408] [rule220_2-deductive-gen403]))

([is_guilty_of_family_violence_lv3-derived-class] of derived-class-inst
   (class-refs rdfs:isDefinedBy rdfs:Resource rdf:type rdfs:Class rdfs:seeAlso rdfs:Resource rdfs:subClassOf rdfs:Class deductive-rules r-device-rule)
   (aliases rdfs:seeAlso rdfs:isDefinedBy)
   (positive 0)
   (negative 0)
   (positive-derivator)
   (negative-derivator)
   (positive-support)
   (negative-support)
   (positive-overruled)
   (negative-overruled)
   (positive-defeated)
   (negative-defeated)
   (proof nil)
   (uri nil)
   (source rdf)
   (lc:name)
   (lc:defendant)
   (lc:uses_weapon)
   (lc:uses_gross_violence)
   (lc:violates_integrity)
   (lc:causes_serious_injury)
   (lc:victim_is_minor)
   (lc:causes_death)
   (lc:violates_protection_measures)
   (lc:legal_obligation_to_support)
   (lc:duty_established_by_court_order)
   (lc:fails_to_pay_support)
   (lc:justified_reasons_for_nonpayment)
   (lc:severe_consequences_for_victim)
   (rdfs:isDefinedBy)
   (rdf:type [rdfs:Class])
   (rdf:value)
   (rdfs:comment)
   (rdfs:label is_guilty_of_family_violence_lv3)
   (rdfs:seeAlso)
   (rdfs:subClassOf [derived-class-inst])
   (stratum 0)
   (deductive-rules [rule220_4_neg_3-deductive-gen412] [rule220_3_b-deductive-gen406] [rule220_3_a-deductive-gen405]))

([is_guilty_of_family_violence_lv4-derived-class] of derived-class-inst
   (class-refs rdfs:isDefinedBy rdfs:Resource rdf:type rdfs:Class rdfs:seeAlso rdfs:Resource rdfs:subClassOf rdfs:Class deductive-rules r-device-rule)
   (aliases rdfs:seeAlso rdfs:isDefinedBy)
   (positive 0)
   (negative 0)
   (positive-derivator)
   (negative-derivator)
   (positive-support)
   (negative-support)
   (positive-overruled)
   (negative-overruled)
   (positive-defeated)
   (negative-defeated)
   (proof nil)
   (uri nil)
   (source rdf)
   (lc:name)
   (lc:defendant)
   (lc:uses_weapon)
   (lc:uses_gross_violence)
   (lc:violates_integrity)
   (lc:causes_serious_injury)
   (lc:victim_is_minor)
   (lc:causes_death)
   (lc:violates_protection_measures)
   (lc:legal_obligation_to_support)
   (lc:duty_established_by_court_order)
   (lc:fails_to_pay_support)
   (lc:justified_reasons_for_nonpayment)
   (lc:severe_consequences_for_victim)
   (rdfs:isDefinedBy)
   (rdf:type [rdfs:Class])
   (rdf:value)
   (rdfs:comment)
   (rdfs:label is_guilty_of_family_violence_lv4)
   (rdfs:seeAlso)
   (rdfs:subClassOf [derived-class-inst])
   (stratum 0)
   (deductive-rules [rule220_4-deductive-gen409]))

([is_guilty_of_violating_measures-derived-class] of derived-class-inst
   (class-refs rdfs:isDefinedBy rdfs:Resource rdf:type rdfs:Class rdfs:seeAlso rdfs:Resource rdfs:subClassOf rdfs:Class deductive-rules r-device-rule)
   (aliases rdfs:seeAlso rdfs:isDefinedBy)
   (positive 0)
   (negative 0)
   (positive-derivator)
   (negative-derivator)
   (positive-support)
   (negative-support)
   (positive-overruled)
   (negative-overruled)
   (positive-defeated)
   (negative-defeated)
   (proof nil)
   (uri nil)
   (source rdf)
   (lc:name)
   (lc:defendant)
   (lc:uses_weapon)
   (lc:uses_gross_violence)
   (lc:violates_integrity)
   (lc:causes_serious_injury)
   (lc:victim_is_minor)
   (lc:causes_death)
   (lc:violates_protection_measures)
   (lc:legal_obligation_to_support)
   (lc:duty_established_by_court_order)
   (lc:fails_to_pay_support)
   (lc:justified_reasons_for_nonpayment)
   (lc:severe_consequences_for_victim)
   (rdfs:isDefinedBy)
   (rdf:type [rdfs:Class])
   (rdf:value)
   (rdfs:comment)
   (rdfs:label is_guilty_of_violating_measures)
   (rdfs:seeAlso)
   (rdfs:subClassOf [derived-class-inst])
   (stratum 0)
   (deductive-rules [rule220_5_neg_4-deductive-gen417] [rule220_5_neg_3-deductive-gen416] [rule220_5_neg_2-deductive-gen415] [rule220_5_neg_1-deductive-gen414] [rule220_5-deductive-gen413]))

([is_guilty_of_nonpayment_of_support_lv1-derived-class] of derived-class-inst
   (class-refs rdfs:isDefinedBy rdfs:Resource rdf:type rdfs:Class rdfs:seeAlso rdfs:Resource rdfs:subClassOf rdfs:Class deductive-rules r-device-rule)
   (aliases rdfs:seeAlso rdfs:isDefinedBy)
   (positive 0)
   (negative 0)
   (positive-derivator)
   (negative-derivator)
   (positive-support)
   (negative-support)
   (positive-overruled)
   (negative-overruled)
   (positive-defeated)
   (negative-defeated)
   (proof nil)
   (uri nil)
   (source rdf)
   (lc:name)
   (lc:defendant)
   (lc:uses_weapon)
   (lc:uses_gross_violence)
   (lc:violates_integrity)
   (lc:causes_serious_injury)
   (lc:victim_is_minor)
   (lc:causes_death)
   (lc:violates_protection_measures)
   (lc:legal_obligation_to_support)
   (lc:duty_established_by_court_order)
   (lc:fails_to_pay_support)
   (lc:justified_reasons_for_nonpayment)
   (lc:severe_consequences_for_victim)
   (rdfs:isDefinedBy)
   (rdf:type [rdfs:Class])
   (rdf:value)
   (rdfs:comment)
   (rdfs:label is_guilty_of_nonpayment_of_support_lv1)
   (rdfs:seeAlso)
   (rdfs:subClassOf [derived-class-inst])
   (stratum 0)
   (deductive-rules [rule221_1_neg_3-deductive-gen421] [rule221_1_neg-deductive-gen419] [rule221_1-deductive-gen418]))

([is_guilty_of_nonpayment_of_support_lv2-derived-class] of derived-class-inst
   (class-refs rdfs:isDefinedBy rdfs:Resource rdf:type rdfs:Class rdfs:seeAlso rdfs:Resource rdfs:subClassOf rdfs:Class deductive-rules r-device-rule)
   (aliases rdfs:seeAlso rdfs:isDefinedBy)
   (positive 0)
   (negative 0)
   (positive-derivator)
   (negative-derivator)
   (positive-support)
   (negative-support)
   (positive-overruled)
   (negative-overruled)
   (positive-defeated)
   (negative-defeated)
   (proof nil)
   (uri nil)
   (source rdf)
   (lc:name)
   (lc:defendant)
   (lc:uses_weapon)
   (lc:uses_gross_violence)
   (lc:violates_integrity)
   (lc:causes_serious_injury)
   (lc:victim_is_minor)
   (lc:causes_death)
   (lc:violates_protection_measures)
   (lc:legal_obligation_to_support)
   (lc:duty_established_by_court_order)
   (lc:fails_to_pay_support)
   (lc:justified_reasons_for_nonpayment)
   (lc:severe_consequences_for_victim)
   (rdfs:isDefinedBy)
   (rdf:type [rdfs:Class])
   (rdf:value)
   (rdfs:comment)
   (rdfs:label is_guilty_of_nonpayment_of_support_lv2)
   (rdfs:seeAlso)
   (rdfs:subClassOf [derived-class-inst])
   (stratum 0)
   (deductive-rules [rule221_3-deductive-gen420]))

([to_pay-derived-class] of derived-class-inst
   (class-refs rdfs:isDefinedBy rdfs:Resource rdf:type rdfs:Class rdfs:seeAlso rdfs:Resource rdfs:subClassOf rdfs:Class deductive-rules r-device-rule)
   (aliases rdfs:seeAlso rdfs:isDefinedBy)
   (positive 0)
   (negative 0)
   (positive-derivator)
   (negative-derivator)
   (positive-support)
   (negative-support)
   (positive-overruled)
   (negative-overruled)
   (positive-defeated)
   (negative-defeated)
   (proof nil)
   (uri nil)
   (source rdf)
   (lc:name)
   (lc:defendant)
   (lc:uses_weapon)
   (lc:uses_gross_violence)
   (lc:violates_integrity)
   (lc:causes_serious_injury)
   (lc:victim_is_minor)
   (lc:causes_death)
   (lc:violates_protection_measures)
   (lc:legal_obligation_to_support)
   (lc:duty_established_by_court_order)
   (lc:fails_to_pay_support)
   (lc:justified_reasons_for_nonpayment)
   (lc:severe_consequences_for_victim)
   (rdfs:isDefinedBy)
   (rdf:type [rdfs:Class])
   (rdf:value)
   (rdfs:comment)
   (rdfs:label to_pay)
   (rdfs:seeAlso)
   (rdfs:subClassOf [derived-class-inst])
   (stratum 0)
   (deductive-rules [pen221_1_fine-deductive-gen432] [pen220_5_fine-deductive-gen430] [pen220_1_fine-deductive-gen422]))

([max_imprisonment-derived-class] of derived-class-inst
   (class-refs rdfs:isDefinedBy rdfs:Resource rdf:type rdfs:Class rdfs:seeAlso rdfs:Resource rdfs:subClassOf rdfs:Class deductive-rules r-device-rule)
   (aliases rdfs:seeAlso rdfs:isDefinedBy)
   (positive 0)
   (negative 0)
   (positive-derivator)
   (negative-derivator)
   (positive-support)
   (negative-support)
   (positive-overruled)
   (negative-overruled)
   (positive-defeated)
   (negative-defeated)
   (proof nil)
   (uri nil)
   (source rdf)
   (lc:name)
   (lc:defendant)
   (lc:uses_weapon)
   (lc:uses_gross_violence)
   (lc:violates_integrity)
   (lc:causes_serious_injury)
   (lc:victim_is_minor)
   (lc:causes_death)
   (lc:violates_protection_measures)
   (lc:legal_obligation_to_support)
   (lc:duty_established_by_court_order)
   (lc:fails_to_pay_support)
   (lc:justified_reasons_for_nonpayment)
   (lc:severe_consequences_for_victim)
   (rdfs:isDefinedBy)
   (rdf:type [rdfs:Class])
   (rdf:value)
   (rdfs:comment)
   (rdfs:label max_imprisonment)
   (rdfs:seeAlso)
   (rdfs:subClassOf [derived-class-inst])
   (stratum 0)
   (deductive-rules [pen221_3_max-deductive-gen435] [pen221_1_prison-deductive-gen433] [pen220_5_prison-deductive-gen431] [pen220_4_max-deductive-gen429] [pen220_3_max-deductive-gen427] [pen220_2_max-deductive-gen425] [pen220_1_prison-deductive-gen423]))

([min_imprisonment-derived-class] of derived-class-inst
   (class-refs rdfs:isDefinedBy rdfs:Resource rdf:type rdfs:Class rdfs:seeAlso rdfs:Resource rdfs:subClassOf rdfs:Class deductive-rules r-device-rule)
   (aliases rdfs:seeAlso rdfs:isDefinedBy)
   (positive 0)
   (negative 0)
   (positive-derivator)
   (negative-derivator)
   (positive-support)
   (negative-support)
   (positive-overruled)
   (negative-overruled)
   (positive-defeated)
   (negative-defeated)
   (proof nil)
   (uri nil)
   (source rdf)
   (lc:name)
   (lc:defendant)
   (lc:uses_weapon)
   (lc:uses_gross_violence)
   (lc:violates_integrity)
   (lc:causes_serious_injury)
   (lc:victim_is_minor)
   (lc:causes_death)
   (lc:violates_protection_measures)
   (lc:legal_obligation_to_support)
   (lc:duty_established_by_court_order)
   (lc:fails_to_pay_support)
   (lc:justified_reasons_for_nonpayment)
   (lc:severe_consequences_for_victim)
   (rdfs:isDefinedBy)
   (rdf:type [rdfs:Class])
   (rdf:value)
   (rdfs:comment)
   (rdfs:label min_imprisonment)
   (rdfs:seeAlso)
   (rdfs:subClassOf [derived-class-inst])
   (stratum 0)
   (deductive-rules [pen221_3_min-deductive-gen434] [pen220_4_min-deductive-gen428] [pen220_3_min-deductive-gen426] [pen220_2_min-deductive-gen424]))

