
(printout t "CWD TEST" crlf)
(load* ".\\DR-DEVICE-source\\defeasible.clp")
(open "rulebase.clp" test "r")
(printout t "RULEBASE FOUND" crlf)
(close test)
(open "where.txt" f "w")
(printout f "Hello from CLIPS" crlf)
(close f)
(dribble-on "rulebase.log")
(batch* "bin\\dr-device.bat")
(set-verbose on)
(set-debug on)
(set-time-report off)
(set-compact-proofs on)
(set-export-non-proved off)
(watch facts)
(watch rules)
(watch activations)
(watch focus)
(watch compilations)
(open "rulebase.clp" in "r")
(open "copy.clp" out "w")

(while (neq (bind ?line (readline in)) EOF)
   do
   (printout out ?line crlf))

(close in)
(close out)
(load-dr-device "rulebase.clp")
(dribble-off)
(exit)
(exit)